---
- hosts: webservers
  remote_user: runner
  become_method: sudo
  become: true

  tasks:
    — name: Install NMAP
      ansible.builtin.apt:
        name: nmap
        state: present

    — name: Scan
      ansible. built in. shell: "nmap { { item } } —p 80 —OG —0
      loop: "{{ lookup('fiIe', './targets.txt').splitlines() }}"
      register: scan_results

    — name: Scan results
    ansible.builtin.debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ scan_results.results }}"
